delete json files
777Matvei777/yadro pull request #10
Opened 2024-04-28 18:06 UTC by 777Matvei777

Здравствуйте! Попытался сделать что то похожее на гексагональную архитектуру, но не совсем уверен, что получилось что то адекватное :) @vbelogrudov

2024-04-30 15:33 UTC, vbelogrudov commented
func NewServer(cfg *config.Config, ctx context.Context) *Server {
	s := &Server{
		Router: http.NewServeMux(),
		Ctx:    ctx,
		Cfg:    cfg,
	}

Мы не храним контекст в структурах. Контекст всегда передается первым параметром функций

2024-04-30 15:40 UTC, vbelogrudov commented
type Handler struct {
	Cfg    *config.Config
	Ctx    context.Context

Мы не храним контекст в структурах и обысно его передаем первым параметром в функции или методы. В данном случае у нас контекст приходит из http сервера, точнее request-a:

func (h *Handler) getPicsHandler(w http.ResponseWriter, r *http.Request) {
   ctx := r.Context()
   // pass context to other functions 

если сервер или реквест останавливаются, ctx это сигнализирует через Done()

2024-04-30 15:51 UTC, vbelogrudov commented
по структуре пока непонятно, где независимая бизнес логика :)
по серверу, было бы здорово защитить update от одновременных вызовов, например, с помощью sync mutex (trylock)

2024-04-30 15:52 UTC, vbelogrudov commented
и еще не хватает "В определенное время сервер сам (раз в сутки) проверяет наличие новых комиксов."

2024-04-30 19:56 UTC, 777Matvei777 commented
Добрый вечер! Исправил ситуацию с контекстом, добавил функцию для проверки наличия новых комиксов раз в сутки. Поставил mu.trylock() на update. Не совсем понимаю что именно в этом проекте является бизнес логикой и как ее сделать независимой :) @vbelogrudov

2024-04-30 20:07 UTC, 777Matvei777 commented
И не очень понятно насчет контекста, если мы его берем из request'а, тогда у нас не будет обрабатываться ситуация ctrl-c, или это уже не нужно для данного задания?

2024-05-02 06:49 UTC, vbelogrudov commented
> И не очень понятно насчет контекста, если мы его берем из request'а, тогда у нас не будет обрабатываться ситуация ctrl-c, или это уже не нужно для данного задания?

хороший вопрос, тут ctrl-C должен сам http сервер отрабатывать, то есть мы в main ловим сигнал и делаем Shutdown этому серверу. https://millhouse.dev/posts/graceful-shutdowns-in-golang-with-signal-notify-context как пример, слегка переусложненный. Можно запустить горутину, в ней ждать Ctrl-C и делать Shutdown()

2024-05-02 07:00 UTC, vbelogrudov requested changes

2024-05-02 07:00 UTC, vbelogrudov commented on pkg/server/handler.go
>  	w.Header().Set("Content-Type", "application/json")
это не спасает от паник, лучше w.Header + json.NewEncode спрятать внутрь лока, иначе у нас h.Comics не защищен от конкурентного доступа

2024-05-03 19:10 UTC, 777Matvei777 commented
Добрый вечер! Добавил w.Header + json.NewEncode в trylock, сделал gracefull Shutdown для сервера, вроде работает :) @vbelogrudov

2024-05-04 13:42 UTC, vbelogrudov requested changes

2024-05-04 13:42 UTC, vbelogrudov commented on pkg/server/handler.go
> +	var mu sync.Mutex
мьютекс должен лежать в структуре Handler, иначе от него здесь нет толка - каждый вызов создает новую переменную mu.
"Ломал" этой командой:
curl -X POST localhost:8080/update & curl -X POST localhost:8080/update

2024-05-04 16:56 UTC, 777Matvei777 commented
Здравствуйте, добавил мьютекс в handler, проверил командой curl -X POST localhost:8080/update & curl -X POST localhost:8080/update, теперь не ломается :) @vbelogrudov

2024-05-05 11:52 UTC, vbelogrudov approved these changes

2024-05-08 09:33 UTC, merged