task6
777Matvei777/yadro pull request #13
Opened 2024-05-13 22:23 UTC by 777Matvei777

Здравствуйте! Сделал с использованием postgresql @vbelogrudov

2024-05-14 07:50 UTC, vbelogrudov commented
Привет!

func (s *Server) AddServer() {
	s.Serv = &http.Server{
		Addr:    s.Cfg.Port,
		Handler: s.Router,
	}
}

этот метод нам не очень нужен и непонятен с точки зрения пользователя, можно спрятать в NewServer

В CreateComic можно сразу сделать defer tx.Rollback(), чтобы меньше писать кода в проверках ошибок, https://stackoverflow.com/questions/46421602/why-defer-a-rollback

2024-05-14 07:51 UTC, vbelogrudov requested changes
после первого старта и остановки сервер больше не стартует:
```
Загружен 2600 комикс
Загружен 2700 комикс
Загружен 2800 комикс
Загружен 2900 комикс
All comics in database
All comics in database
^C%                                                                                                                                               
➜  777Matvei777/yadro git:(master) ✗ ./xkcd -c config.yaml
2024/05/14 10:49:37 <nil>
2024/05/14 10:49:37 no change
➜  777Matvei777/yadro git:(master) ✗ ./xkcd -c config.yaml
2024/05/14 10:49:43 <nil>
2024/05/14 10:49:43 no change
➜  777Matvei777/yadro git:(master) ✗ 

```

2024-05-14 20:28 UTC, 777Matvei777 commented
Здравствуйте! Убрал RunServer за ненадобностью, прописал defer tx.Rollback(), Исправил ситуацию с тем, что сервер второй раз не запускается, после того, как его роняют. На сколько я понял, это было связано с тем, что версии миграции up ничем не отличалась от той, что была запущена при первом запуске. Из за этого выскакивала ошибка. Нашел решение, но в его правильности не совсем уверен :) @vbelogrudov

2024-05-15 09:27 UTC, vbelogrudov requested changes
Привет!

все работает!

2024-05-15 20:38 UTC, merged