task2
777Matvei777/yadro pull request #4
Opened 2024-04-05 12:09 UTC by 777Matvei777

Добрый день, надеюсь я правильно понял все организационные моменты насчет PR в гитхабе. По заданию не до конца понимаю функционал флага -o, пока сделал как есть.

2024-04-05 15:38 UTC, vbelogrudov commented
с ПР все в порядке. будем его смотреть. -o позволяет вывести часть базы данных (с -n) или полностью на экран

2024-04-05 15:53 UTC, vbelogrudov commented
из текущих недочетов -

1. программа не строится через make
2. нет прогресса, например, каждые закаченный 100 комиксов
3. все, что связано с xkcd сайтом и его структурами, должно быть в pkg/xkcd
4. pkg/database не должен знать о pkg/xkcd и о pkg/words
5. можно сделать связку всех pkg библиотек в main пакете или еще одном pkg/app, например
6. желательно найти способ более гибкого нахождения последнего комикса
7. client := &http.Client{} <- сюда можно добавить таймаут на запрос, иначе в клиенте нет смысла, можно просто http.Get(..)
8. db_file - полный путь к файлу базы, нет необходимости его прятать в pkg/database
9. для Базы можно создать тип Database struct { path string, data map[string]Comics} и к нему методы Get, Add, Save и функцию New(path string) которая будет этот объект инициализировать - считывать существующий json, если таковой есть.

2024-04-07 11:11 UTC, 777Matvei777 commented
Добрый день, постарался исправить существующие недочеты так, как я их понимаю @vbelogrudov

2024-04-07 12:32 UTC, vbelogrudov requested changes
привет, есть небольшие замечания в коде, по структуре - у нас database зависит от app, а должно быть наоборот. main в идеале должен знать только app

2024-04-07 12:32 UTC, vbelogrudov commented on pkg/xkcd/client.go
> +		resp, _ := http.Get(adress)
здесь может возникнуть и не http ошибка, стоит все равно проверить

2024-04-07 12:32 UTC, vbelogrudov commented on pkg/xkcd/client.go
> +		if resp.StatusCode == 404 && i != 404 {
проверку кода лучше сдвинуть вниз после defer resp.Body.Close()

2024-04-07 12:32 UTC, vbelogrudov commented on pkg/xkcd/client.go
> +		_ = json.Unmarshal([]byte(data), &one_data)
нет проверки на валидность json-a

2024-04-07 12:32 UTC, vbelogrudov commented on pkg/xkcd/client.go
> +var Db []XkcdStruct
Db лучше возвращать из  Parse(), нам нет необходимости хранить базы в глобальной переменной

2024-04-07 12:35 UTC, vbelogrudov commented
программа должна загрузить все комиксы в базу без флагов  -n или -o

2024-04-07 16:17 UTC, 777Matvei777 commented
Еще раз добрый день :). Недочеты учел и вроде как исправил @vbelogrudov

2024-04-08 17:00 UTC, merged