task3
777Matvei777/yadro pull request #6
Opened 2024-04-12 20:11 UTC by 777Matvei777

Добрый вечер. Вроде сделал все, что требовалось, за исключением задания со звездочкой. Возможно, обоснование числа горутин не совсем объективное... @vbelogrudov

2024-04-14 15:09 UTC, vbelogrudov commented
привет!

1. не хватает go mod tidy
2. build в Makefile, BINARY var unused
3. 	Db_file  string `yaml:"db_file"` - обычно используем camel/pascal case, то есть DbFile или DBFile
4.  в normalization.go, Stemming - Contains очень неэффективен при количестве слов > 10, лучше сделать промежуточный map[string]bool и через него проверять уже существующие слова. Иначе можно также slices.Contains, чтобы без велосипедов
5. в CreateDatabase фактически отсутствует работа с ошибками
6. for излишен. Также можно упростить с помощью signal.NotifyContext
```
	go func() {
		for {
			<-ch
			cancelFunc()
		}
	}()
```
7. много логики в main . app.Start сам может создать/прочитать базу
8. exist можно сделать map[int]bool
9. xkcd/client.go - found404 нигде не заполняется

2024-04-14 15:11 UTC, vbelogrudov requested changes
есть небольшие замечания, в остальном все работает как надо

2024-04-14 19:54 UTC, 777Matvei777 commented
Доброго времени суток! Вроде все недочеты учел и исправил. @vbelogrudov

2024-04-15 18:50 UTC, vbelogrudov reviewed
маленькие замечания, в остальном все работает как надо

2024-04-15 18:50 UTC, vbelogrudov commented on pkg/words/normalization.go
> +					if _, ok := contains[stemmed]; !ok {
можно еще чуть короче,
```
if ! contains[stemmed] {
    append
```

2024-04-15 18:50 UTC, vbelogrudov commented on pkg/database/database.go
>  func CreateDataBase(data map[int]interface{}, Db_path string) {
как-то много маршалинга и анмаршалинга.

2024-04-15 18:50 UTC, vbelogrudov commented on pkg/app/app.go
>  	select {}
?

2024-04-16 17:14 UTC, 777Matvei777 commented
Добрый вечер, недочеты убрал. Не знаю как там оказалось select{}, наверное не уследил :) @vbelogrudov

2024-04-16 18:14 UTC, vbelogrudov approved these changes

2024-04-16 20:24 UTC, merged